apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-pv
  labels:
    name: bookstore-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: default
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstore-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  selector:
    matchLabels:
      name: bookstore-pv